# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-10 03:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publicacion',
            managers=[
                ('lolo_publish', django.db.models.manager.Manager()),
            ],
        ),
    ]
