# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-14 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0002_auto_20170210_0328'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publicacion',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Publicaciones/'),
        ),
    ]
